### ISSUE TITLE
Cannot PreventDefault behavior on "view.AddListener()" elements 

### ISSUE THREAD

**Issue by fabioberger** [go-humble/humble#1]
When adding a listener on an event such as: 

``` go
if err := view.AddListener(r, "a.remove", "click", r.deleteClicked); err != nil {
        return err
    }
```

When the link is clicked, it's default behavior still activates even when `event.PreventDefault()` is called in the event handler function. Right now the work around is to write:

``` html
<a href="javascript:void(0)" class="remove">X</a>
```

But it would be nice to prevent default behavior from within the callback.

**Comment by albrow** [comment]
Okay. I know it's been a while. We are rewriting a lot of components. I know how to fix this bug and I am able to call `event.PreventDefault()` successfully in the [latest router package](https://github.com/go-humble/humble/blob/1dfdfb385d814cd236153f2e4be7d2bf246aa00e/router/router.go#L191). All I had to do was set the `useCapture` parameter to `true` when calling [`AddEventListener`](https://godoc.org/honnef.co/go/js/dom#BasicNode.AddEventListener) whereas in the [current master branch](https://github.com/go-humble/humble/blob/master/view/view.go#L225) we have it set to `false`. I'm thinking about how events should work in the new view package. They might not be included in the next minor release, but whenever they are I will definitely fix this.
