### ISSUE TITLE
TodoMVC project layout and alternative model approach

### ISSUE THREAD

**Issue by cryptix** [go-humble/humble#8]
Hey,

I made a [fork](https://github.com/cryptix/exp/tree/master/humbleRpcTodo) of the TodoMVC example and consolidated it into single repository.

Having the code in two places felt weird (especially firing up a 2nd web server for the html/js/css). Maybe you should just outline the ability to speak to multiple REST backends with this approach but it felt unnecessary for an introduction example.

Have you seen [this](https://github.com/shurcooL/play/commit/e7e89367c071462ed0d150663bba54a78c06deed) demo of using [net/rpc](https://golang.org/pkg/net/rpc) over websockets? I applied it to this example and I urge you to take a look at it - it deletes so much marshaling and parameter decoding code. My execution is a bit whacky (directly using `client.Call`, having the client sit in the `AppView`) but a proper implementation could use the same interface for the rpc client as well as the backend.

ps: Maybe refactor the example a bit with regards to error handling. All the `panic(err)`s tingle my gophersenses.

Despite all that: Thanks for this really interesting project!

**Comment by soroushjp** [comment]
Thank you cryptix -- just writing quickly to let you know that I've been a little busy but that I fully intend to look through your issue in detail in the next 2 weeks. I'll be thinking about net/rpc implementation, and I think you're almost certainly right about the TodoMVC organization. More to come shortly!

**Comment by albrow** [comment]
This issue is pretty old and the TodoMVC example has changed considerably from the time it was first opened. It now works completely on the client-side and doesn't require a server. I'm going to close this.
